### ISSUE TITLE
PRD management procedure table has very high harvest rate (HR = 0.93)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#122]
Table 29 (code chunk `decision-prd`) is the management procedure table for PRD. The harvest rate column indicates HR = 0.93 for the four MPs with "cap2.5". Seems too high/incorrect.

- HS50-60_HR20_cap2.5 (DDM and DIM)
- HS30-60_HR10_cap2.5 (DDM and DIM)

https://github.com/pbs-assess/herringsr/blob/106df0e40a3ae9e5cd60d495462f5c3363102b8e/english/05_tables.Rmd#L960

![PRD_MP](https://user-images.githubusercontent.com/25674027/190688443-a6d6b7b3-21aa-4fa1-a040-1215255e65d7.png)

**Comment by Sages11** [comment]
Fixed with commit  #f2d08cf. 
hr <- catch.cat/bt   instead of hr <- (bt-catch.cap)/bt

**Comment by Sages11** [comment]
The recommended total allowable catch (TAC)
and associated harvest rate (HR) are reported for each MP based on their posterior densities. HR is not the median posterior density of the TAC divided by the median posterior density of the SB_t.   Some more investigation is needed to determine if the reported values are medians or means of the posterior densities.

**Comment by Sages11** [comment]
For the 2022 SR the table header is changed to, "...The recommended total allowable catch (TAC)
and associated harvest rate (HR) are calculated for each MP using their posterior densities values.   ...."

**Comment by Sages11** [comment]
If the harvest rates are s based on the median of the TAC/B_t (for each of the currently 4000 iterations) Then the values are as we would like them to be. If it is the mean, then we would probably want it to change to median. (Not wrong per se, but not preferred.) Either way we would like the header in the future to specify the mean or median of the posterior densities.     For further clarity, this issue was tagged, since the table value of TAC divided by estimated B_t  (both which are medians of their posterior densities) did not equal the table HR value.    This way of calculating woudl not be the recommended way of calculating if you were interested in the estimated HR value.
