### ISSUE TITLE
Fix font issue with everyone

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/herringsr#20]
I have the correct font, I think it's Arial but I noticed Jaclyn and Matt at least have what looks like Times New Roman.

**Comment by Shawkshaw** [comment]
I have Times New Roman as well

**Comment by cgrandin** [comment]
If you rebase and reinstall csasdown I have tried to fix it. The style file now has helvet type shich is the same as the res doc so hopefully that works.

**Comment by cgrandin** [comment]
Is this working for everyone? If so close

**Comment by Shawkshaw** [comment]
I am still having trouble with this... If I revert the csasdown commits to sr.sty rebase and rebuild, I can build the sr with the wrong font.  Otherwise I have the following error: (perhaps and issue with my PATH environment variables?)

tlmgr search --file --global "/helvet.sty"
Trying to automatically install missing LaTeX packages...
tlmgr.pl: package repository http://ctan.forsale.plus/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: psnfss [12k]
tar: Skipping to next file header
TLUtils::untar: C:\Users\hawkshaws\AppData\Roaming\TinyTeX\tlpkg\installer\tar.exe xmf C:\Users\HAWKSH~1\AppData\Local\Temp\1\CQQ6ak7REF\3ze6iUxX3y/psnfss.tar failed (in C:/Users/hawkshaws/AppData/Roaming/TinyTeX/texmf-dist)
TLPDB::_install_package: untar failed
tlmgr.pl: package log updated: C:/Users/hawkshaws/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
tlmgr search --file --global "/helvet.sty"
! LaTeX Error: File `helvet.sty' not found.

**Comment by cgrandin** [comment]
What does this return:
```
tinytex::tlmgr_search("/helvet.sty")
```

**Comment by cgrandin** [comment]
If not installed.. try:

```
tinytex::tlmgr_install("helvet")
```

**Comment by Shawkshaw** [comment]
I am receiving an error for both these:

> tinytex:::tlmgr_search("/helvet.sty")
tlmgr search --file --global "/helvet.sty"
xz: (stdin): Compressed data is corrupt
tlmgr.pl: package repository http://ctan.mirror.colo-serv.net/systems/texlive/tlnet (not verified: gpg unavailable)
psnfss:
	texmf-dist/tex/latex/psnfss/helvet.sty

AND

> tinytex::tlmgr_install("helvet")
tlmgr install helvet
xz: (stdin): Compressed data is corrupt
tlmgr.pl: Fundamental package texlive.infra not present, uh oh, goodbyeShould not happen, texlive.infra not found at C:\Users\HAWKSH~1\AppData\Roaming\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 7379.
tlmgr.pl: package repository http://ctan.mirror.colo-serv.net/systems/texlive/tlnet (not verified: gpg unavailable)

**Comment by cgrandin** [comment]
You still have the xz problem. You need to find xz.exe on your path and rename it to xz_old.exe
On my machine (and @grinnellm's) it is located at C:\mingw\msys\bin

**Comment by Shawkshaw** [comment]
Horray this worked! Thanks!
