### ISSUE TITLE
Add figure for A2W with timeseries of the proportion of spawn in each section

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#80]
![image](https://user-images.githubusercontent.com/6414082/125386704-95cc9180-e351-11eb-8f32-19ceee54c7c2.png)
Like this one in the data summaries without the middle panel maybe?

**Comment by jaclyncleary** [comment]
Please also include a table with the last 10-years (same as SR Table 4-8) so that we have short term and long term trends.

**Comment by grinnellm** [comment]
I added tables for A27 and A2W. Instead of that figure, can we add the same one we use for CC spawn by section (below)? We already have the upper panel as a separate figure (Figure 17; `minor-spawn-index-fig`), and I'm not a big fan of the stacked bars in the lower panel. If we do the same as CC, I also have the code and data ready to go, so would be easy to implement.
![image](https://user-images.githubusercontent.com/25674027/127208447-302d0efc-2066-421e-8533-03423195b5ad.png)

**Comment by jaclyncleary** [comment]
great idea
