### ISSUE TITLE
revise figure caption for storyboard plot

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#95]
Collectively we have reduced the caption from 17 to 12 lines.  The end/ committed result is a mix of suggestions from SP and the original.
Still to do:

- [x] read it through
- [x] edit french caption 
- [x] add storyboard caption to each storyboard figure (to make it easier for the Nations/ stakeholders from a given area to focus on their stock figure)

**Comment by grinnellm** [comment]
I created the original issue about the storyboard caption being too long, but now I think it's a bit too short. It's really 6 captions in one, so we can expect it to be longer than most. To me, a few more words would help with reading/flow. This would also make it consistent with the style of the other table and figure captions, and make it self-contained. I don't think there is much to lose from making it a bit longer; the overall figure aspect ratio is nice, and the aspect ratio for the individual panels is nice. That is, I don't think we would want each panel to be taller. Maybe a bit taller to fit in the extra Year axes, but not much.

The first sentence is a bit awkward (in my opinion). There is some missing information in a few places (e.g., what are the circles and triangles in panel a?). There's a small typo in (b) re the "year-1" and I think we should just provide the reference to the catch figure in (d), instead of describing the colours (they could change, and those descriptions don't work for colour-blind readers or greyscale printing). One more thing I might add is to make the "Panel (x)" parts in the caption either **bold** or _italic_ to help readers find their way. Not sure if CSAS would approve that formatting, but we can try it and see:)

Once we are happy with the caption, we should take all but the fist sentence and make it into a variable. That way we can just edit one variable instead of editing each of the 5 figures for any future changes.

I am happy to make those changes if you would like. I can also make this into a variable and make the French translation too. Let me know. Feels like this has gone back and forth a bit, and I would like to avoid conflicts if possible.

**Comment by Sages11** [comment]
Like the variable bit an the bold idea. I am changing other figure captions so maybe look at those for consistency.

**Comment by grinnellm** [comment]
French caption is not done, but I can either translate it or add this to the jobs when we translate the main document. Otherwise I think this is done in https://github.com/pbs-assess/herringsr/commit/f8e4c20bf5ca697cb19f69a484c5b833902f916b.

**Comment by grinnellm** [comment]
Made a TODO for the French translation.
